//! Build-time trie generator.
//!
//! Usage (driven by build.zig, not run by hand):
//!   gen_trie <out_dir> <eol> <table.txt> [<table.txt> ...]
//!
//! Reads each table file (lines of "<value>\t<keys>" with '#' comments),
//! builds the trie via `trie.buildBlob` at native speed, then writes:
//!
//!   <out_dir>/trie.bin              — the on-disk format (see blob_format.zig)
//!   <out_dir>/trie_blob_module.zig  — a tiny wrapper that exposes
//!                                     `pub const bytes = @embedFile("trie.bin");`
//!
//! The wrapper sits next to trie.bin so `@embedFile` resolves correctly when
//! the consumer module imports it.

const std = @import("std");
// `trie` is wired in by build.zig as a named module so this script doesn't
// need to reach across the package boundary into ../src/.
const trie = @import("trie");

fn parseTables(
    arena: std.mem.Allocator,
    io: std.Io,
    paths: []const []const u8,
    eol: []const u8,
) ![]trie.Entry {
    var entries: std.ArrayList(trie.Entry) = .empty;
    const cwd = std.Io.Dir.cwd();

    for (paths) |path| {
        const data = try cwd.readFileAlloc(io, path, arena, .limited(1 << 30));

        var it = std.mem.splitSequence(u8, data, eol);
        while (it.next()) |raw_line| {
            const trimmed = std.mem.trim(u8, raw_line, " \r");
            if (trimmed.len == 0 or trimmed[0] == '#') continue;

            const tab = std.mem.indexOfScalar(u8, trimmed, '\t') orelse {
                std.debug.print("error: line without TAB in {s}: {s}\n", .{ path, trimmed });
                return error.MalformedTableLine;
            };
            const value = std.mem.trim(u8, trimmed[0..tab], " ");
            const keys = std.mem.trim(u8, trimmed[tab + 1 ..], " ");
            if (keys.len == 0) continue;

            try entries.append(arena, .{ .keys = keys, .value = value });
        }
    }

    return entries.toOwnedSlice(arena);
}

pub fn main(init: std.process.Init.Minimal) !void {
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    var arena_state = std.heap.ArenaAllocator.init(gpa.allocator());
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    var threaded: std.Io.Threaded = .init(gpa.allocator(), .{
        .environ = init.environ,
        .argv0 = .init(init.args),
    });
    defer threaded.deinit();
    const io = threaded.io();

    const raw_args = try init.args.toSlice(arena);
    if (raw_args.len < 4) {
        std.debug.print("usage: gen_trie <out_dir> <eol> <table.txt> [<table.txt> ...]\n", .{});
        return error.MissingArgs;
    }
    const out_dir_path = raw_args[1];
    const eol_arg = raw_args[2];
    const table_paths = raw_args[3..];

    const eol: []const u8 = if (std.mem.eql(u8, eol_arg, "lf"))
        "\n"
    else if (std.mem.eql(u8, eol_arg, "crlf"))
        "\r\n"
    else
        eol_arg;

    const entries = try parseTables(arena, io, table_paths, eol);
    const blob = try trie.buildBlob(arena, entries);

    const cwd = std.Io.Dir.cwd();
    var out_dir = try cwd.createDirPathOpen(io, out_dir_path, .{});
    defer out_dir.close(io);

    try out_dir.writeFile(io, .{ .sub_path = "trie.bin", .data = blob });
    try out_dir.writeFile(io, .{
        .sub_path = "trie_blob_module.zig",
        .data =
        \\//! Auto-generated by scripts/gen_trie.zig — do not edit.
        \\pub const bytes align(4) = @embedFile("trie.bin").*;
        \\
        ,
    });

    std.debug.print(
        "gen_trie: {d} entries → {d} bytes blob\n",
        .{ entries.len, blob.len },
    );
}
