//! Build-time trie generator.
//!
//! Usage (driven by build.zig, not run by hand):
//!   gen_trie <out_dir> <eol> <target_endian> <table.txt> [<table.txt> ...]
//!
//! `target_endian` is "le" or "be" — gen_trie runs on the host, so when the
//! target's endianness differs from the host's, `trie.buildBlob` byte-swaps
//! every u32 field before writing the blob to disk.
//!
//! Reads each table file (lines of "<value>\t<keys>" with '#' comments),
//! builds the trie via `trie.buildBlob`, then writes:
//!
//!   <out_dir>/trie.bin              — the on-disk format (see blob_format.zig)
//!   <out_dir>/trie_blob_module.zig  — a tiny wrapper that exposes
//!                                     `pub const bytes = @embedFile("trie.bin");`
//!
//! The wrapper sits next to trie.bin so `@embedFile` resolves correctly when
//! the consumer module imports it.

const std = @import("std");
const builtin = @import("builtin");
const testing = std.testing;
// `trie` is wired in by build.zig as a named module so this script doesn't
// need to reach across the package boundary into ../src/.
const trie = @import("trie");

/// Diagnostic print that stays silent under `zig build test`. The unit tests
/// below intentionally exercise the parse-error branches; without this gate,
/// each `expectError` would push an `error: ...` line onto the test runner's
/// captured stderr, which Zig 0.16's build runner then renders as a (bogus)
/// "failed command" block — even when every test passes.
fn diag(comptime fmt: []const u8, args: anytype) void {
    if (!builtin.is_test) std.debug.print(fmt, args);
}

/// Parse the contents of a single table file. Split from `parseTables` so
/// the parsing logic can be unit-tested without touching the filesystem.
fn parseTable(
    arena: std.mem.Allocator,
    out: *std.ArrayList(trie.Entry),
    data: []const u8,
    eol: []const u8,
    path: []const u8,
) !void {
    var it = std.mem.splitSequence(u8, data, eol);
    while (it.next()) |raw_line| {
        const trimmed = std.mem.trim(u8, raw_line, " \r");
        if (trimmed.len == 0 or trimmed[0] == '#') continue;

        const tab = std.mem.indexOfScalar(u8, trimmed, '\t') orelse {
            diag("error: line without TAB in {s}: {s}\n", .{ path, trimmed });
            return error.MalformedTableLine;
        };
        const value = std.mem.trim(u8, trimmed[0..tab], " ");
        const keys = std.mem.trim(u8, trimmed[tab + 1 ..], " ");
        if (keys.len == 0) continue;

        try out.append(arena, .{ .keys = keys, .value = value });
    }
}

fn parseTables(
    arena: std.mem.Allocator,
    io: std.Io,
    paths: []const []const u8,
    eol: []const u8,
) ![]trie.Entry {
    var entries: std.ArrayList(trie.Entry) = .empty;
    const cwd = std.Io.Dir.cwd();

    for (paths) |path| {
        const data = try cwd.readFileAlloc(io, path, arena, .limited(1 << 30));
        try parseTable(arena, &entries, data, eol, path);
    }

    return entries.toOwnedSlice(arena);
}

pub fn main(init: std.process.Init.Minimal) !void {
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    var arena_state = std.heap.ArenaAllocator.init(gpa.allocator());
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    var threaded: std.Io.Threaded = .init(gpa.allocator(), .{
        .environ = init.environ,
        .argv0 = .init(init.args),
    });
    defer threaded.deinit();
    const io = threaded.io();

    const raw_args = try init.args.toSlice(arena);
    if (raw_args.len < 5) {
        std.debug.print("usage: gen_trie <out_dir> <eol> <target_endian> <table.txt> [<table.txt> ...]\n", .{});
        return error.MissingArgs;
    }
    const out_dir_path = raw_args[1];
    const eol_arg = raw_args[2];
    const endian_arg = raw_args[3];
    const table_paths = raw_args[4..];

    const eol: []const u8 = if (std.mem.eql(u8, eol_arg, "lf"))
        "\n"
    else if (std.mem.eql(u8, eol_arg, "crlf"))
        "\r\n"
    else
        eol_arg;

    const target_endian: std.builtin.Endian = blk: {
        if (std.mem.eql(u8, endian_arg, "le")) break :blk .little;
        if (std.mem.eql(u8, endian_arg, "be")) break :blk .big;
        std.debug.print("error: unknown target endianness {s} (expected \"le\" or \"be\")\n", .{endian_arg});
        return error.BadEndianArg;
    };

    const entries = try parseTables(arena, io, table_paths, eol);
    const blob = try trie.buildBlob(arena, entries, target_endian);

    const cwd = std.Io.Dir.cwd();
    var out_dir = try cwd.createDirPathOpen(io, out_dir_path, .{});
    defer out_dir.close(io);

    try out_dir.writeFile(io, .{ .sub_path = "trie.bin", .data = blob });
    try out_dir.writeFile(io, .{
        .sub_path = "trie_blob_module.zig",
        .data =
        \\//! Auto-generated by scripts/gen_trie.zig — do not edit.
        \\pub const bytes align(4) = @embedFile("trie.bin").*;
        \\
        ,
    });

    // Re-parse the blob locally to surface the worst-case caps it embedded.
    // These dictate per-context memory in `jd_init`; logging them gives early
    // visibility into the per-context resident size.
    //
    // Write to stdout (not stderr): zig build's Run step captures stderr when
    // a step has output args and the build runner then renders it as a "failed
    // command" even on exit 0. Informational lines belong on stdout.
    const t = try trie.Trie.fromBytes(blob);
    const msg = try std.fmt.allocPrint(
        arena,
        "gen_trie: {d} entries → {d} bytes blob (frontier_cap={d}, path_buf_cap={d})\n",
        .{ entries.len, blob.len, t.frontier_cap, t.path_buf_cap },
    );
    try std.Io.File.stdout().writeStreamingAll(io, msg);
}

// =========================================================================
// Tests
// =========================================================================

const ParseFixture = struct {
    arena_state: std.heap.ArenaAllocator,
    entries: std.ArrayList(trie.Entry),

    fn init() ParseFixture {
        return .{
            .arena_state = std.heap.ArenaAllocator.init(testing.allocator),
            .entries = .empty,
        };
    }

    fn deinit(self: *ParseFixture) void {
        self.arena_state.deinit();
    }

    fn arena(self: *ParseFixture) std.mem.Allocator {
        return self.arena_state.allocator();
    }
};

test "parseTable: single line parses value\\tkeys" {
    var f = ParseFixture.init();
    defer f.deinit();

    try parseTable(f.arena(), &f.entries, "甲\ta\n", "\n", "test.txt");
    try testing.expectEqual(@as(usize, 1), f.entries.items.len);
    try testing.expectEqualStrings("甲", f.entries.items[0].value);
    try testing.expectEqualStrings("a", f.entries.items[0].keys);
}

test "parseTable: multiple lines" {
    var f = ParseFixture.init();
    defer f.deinit();

    try parseTable(f.arena(), &f.entries, "甲\ta\n乙\tab\n丙\tabc\n", "\n", "test.txt");
    try testing.expectEqual(@as(usize, 3), f.entries.items.len);
    try testing.expectEqualStrings("乙", f.entries.items[1].value);
    try testing.expectEqualStrings("ab", f.entries.items[1].keys);
}

test "parseTable: skips comments and blank lines" {
    var f = ParseFixture.init();
    defer f.deinit();

    try parseTable(
        f.arena(),
        &f.entries,
        "# header comment\n" ++
            "\n" ++
            "甲\ta\n" ++
            "# mid comment\n" ++
            "\n" ++
            "乙\tab\n",
        "\n",
        "test.txt",
    );
    try testing.expectEqual(@as(usize, 2), f.entries.items.len);
}

test "parseTable: line without TAB is an error" {
    var f = ParseFixture.init();
    defer f.deinit();

    try testing.expectError(error.MalformedTableLine, parseTable(f.arena(), &f.entries, "no-tab-here\n", "\n", "test.txt"));
}

test "parseTable: empty keys silently skipped" {
    var f = ParseFixture.init();
    defer f.deinit();

    // A line like "value\t" (or "value\t   ") has empty trimmed keys and is dropped.
    try parseTable(f.arena(), &f.entries, "甲\ta\n乙\t   \n丙\tc\n", "\n", "test.txt");
    try testing.expectEqual(@as(usize, 2), f.entries.items.len);
    try testing.expectEqualStrings("甲", f.entries.items[0].value);
    try testing.expectEqualStrings("丙", f.entries.items[1].value);
}

test "parseTable: trims surrounding spaces" {
    var f = ParseFixture.init();
    defer f.deinit();

    try parseTable(f.arena(), &f.entries, "  甲  \t  a  \n", "\n", "test.txt");
    try testing.expectEqual(@as(usize, 1), f.entries.items.len);
    try testing.expectEqualStrings("甲", f.entries.items[0].value);
    try testing.expectEqualStrings("a", f.entries.items[0].keys);
}

test "parseTable: CRLF line endings" {
    var f = ParseFixture.init();
    defer f.deinit();

    try parseTable(f.arena(), &f.entries, "甲\ta\r\n乙\tab\r\n", "\r\n", "test.txt");
    try testing.expectEqual(@as(usize, 2), f.entries.items.len);
    try testing.expectEqualStrings("ab", f.entries.items[1].keys);
}

test "parseTable: appends to existing entries" {
    var f = ParseFixture.init();
    defer f.deinit();

    try parseTable(f.arena(), &f.entries, "甲\ta\n", "\n", "first.txt");
    try parseTable(f.arena(), &f.entries, "乙\tb\n", "\n", "second.txt");
    try testing.expectEqual(@as(usize, 2), f.entries.items.len);
    try testing.expectEqualStrings("甲", f.entries.items[0].value);
    try testing.expectEqualStrings("乙", f.entries.items[1].value);
}
